### ISSUE TITLE
ARM Support!

### ISSUE THREAD

**Issue by SohumB** [robusta-dev/robusta#278]
Most of the images you're using are multiarch, so Robusta is almost fully built for ARM, but there are three that are x86 only: 

* `us-central1-docker.pkg.dev/genuine-flight-317411/devel/kubewatch:v1.11`
* `us-central1-docker.pkg.dev/genuine-flight-317411/devel/grafana-renderer:6`
* `us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:0.9.4`

It'd be great if there were multi-arch builds for these as well!

**Comment by aantn** [comment]
Yep, completely agree. Don't have an ETA for this yet but we'll get to it!

**Comment by VladoPortos** [comment]
Same, was going to give a Robusta try, but my cluster is ARM64, could not get it to run :( 

```
root@control01:~# kubectl logs robusta-forwarder-7f444db6f4-hrms4 -n robusta    
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by d3v2null** [comment]
Unfortunately lack of multi-arch with arm64 support is not what I expected. 
This is a blocker for adopting Robusta in our EKS clusters.

**Comment by arikalon1** [comment]
@anFatum started working on it

**Comment by anFatum** [comment]
It was resolved in #508 PR and released in 0.10.4.

Please provide feedback and let us know once you start using it!

**Comment by oxeye-meir** [comment]
Still doesn't work for me.
➜  Robusta robusta version                                
version 0.10.8
➜  Robusta kubectl logs robusta-forwarder-76f56bbbc5-ftmzz
exec /bin/kubewatch: exec format error

**Comment by RoiGlinik** [comment]
@oxeye-meir I am checking this , Will ping you with an update

**Comment by RoiGlinik** [comment]
@oxeye-meir , We added ARM image for the robusta-forwarder. Please let me know if it works for you

**Comment by oxeye-meir** [comment]
Wonderful.
Thanks a lot, looks like it's working now :-)

**Comment by tuananh** [comment]
we use Chainguard's kubewatch (`cgr.dev/chainguard/kubewatch`) and it's multi-arch

https://github.com/chainguard-images/images/tree/main/images/kubewatch
